export const THEMES = {
  NavyBlue:      { bg: '#0D1117', accent: '#4A90D9', name: 'Navy + Blue',    slug: 'navy_blue' },
  NavyTeal:      { bg: '#0D1117', accent: '#2DD4BF', name: 'Navy + Teal',    slug: 'navy_teal' },
  NavyPurple:    { bg: '#0D1117', accent: '#8B5CF6', name: 'Navy + Purple',  slug: 'navy_purple' },
  CharcoalOrange:{ bg: '#1A1A1A', accent: '#F97316', name: 'Charcoal + Orange', slug: 'charcoal_orange' },
  DeepGreen:     { bg: '#0A2218', accent: '#FFFFFF', name: 'Deep Green + White', slug: 'deep_green' },
  MidnightCoral: { bg: '#12071A', accent: '#FF6B6B', name: 'Midnight + Coral',  slug: 'midnight_coral' },
}

export const TEMPLATE_LABELS = {
  BigHeadline: 'Big Headline',
  Split:       'Split',
  Quote:       'Quote',
  Stat:        'Stat',
  CTA:         'CTA',
  Story:       'Story',
}

export const ALL_POSTS = [
  { id:1,  week:1,  template:'BigHeadline', theme:'NavyBlue',       cta:'', headline:'We build digital foundations for businesses ready to grow.',             subtext:'Websites. E-commerce. Admin panels. Mobile apps. Built properly, the first time.',                                     caption:"Layer1 Studio is officially on LinkedIn. We're a Sri Lanka-based tech studio that builds clean, functional digital products for SMEs and startups. No fluff. Just solid builds. If you're building something — let's talk. layer1.studio" },
  { id:2,  week:2,  template:'Story',       theme:'NavyPurple',     cta:'', headline:'Built by developers who hold their work to an international standard.',  subtext:"We've worked in enterprise data teams and published AI research. That's the bar we bring to every build.",             caption:"Layer1 Studio was founded by developers who also publish AI research and work at enterprise-level data teams. Every client project — however big or small — gets that same standard. layer1.studio" },
  { id:3,  week:3,  template:'Stat',        theme:'NavyTeal',       cta:'', headline:'Your online store should work as hard as you do.',                       subtext:'We build e-commerce platforms that are fast, easy to manage, and built to convert.',                                    caption:"We've built e-commerce solutions for food brands, lifestyle businesses, and creative entrepreneurs across Sri Lanka. Every store comes with a custom admin panel so you're always in control. layer1.studio" },
  { id:4,  week:4,  template:'BigHeadline', theme:'CharcoalOrange', cta:'', headline:'Stop managing your business on WhatsApp.',                               subtext:'A custom admin panel puts you in control — orders, inventory, customers, all in one place.',                          caption:'Most small businesses are running their operations across WhatsApp, spreadsheets, and sticky notes. We build custom admin panels that bring everything together. Clean. Simple. Yours. layer1.studio' },
  { id:5,  week:5,  template:'Split',       theme:'NavyBlue',       cta:'', headline:'A website is just the start.',                                           subtext:'The businesses growing fastest online have systems — not just pages.',                                               caption:'Most SMEs stop at a website. The ones winning digitally have built systems — inventory management, order tracking, customer dashboards. That\'s what we build at Layer1. layer1.studio' },
  { id:6,  week:6,  template:'CTA',         theme:'MidnightCoral',  cta:'Book a call. Let\'s build something real.', headline:'Your customers are on their phones. Are you?', subtext:"We build mobile apps that give your business a presence in your customer's pocket.", caption:"A mobile app isn't just for big companies anymore. We build clean, functional apps for gyms, retailers, and service businesses that want to stay connected with their customers. layer1.studio" },
  { id:7,  week:7,  template:'Story',       theme:'NavyTeal',       cta:'', headline:'From kitchen to checkout in one build.',                                 subtext:"We built Ambrosia's full e-commerce platform and admin panel so they could sell and manage — all in one place.",   caption:"Ambrosia needed more than a pretty website. They needed a system. We built their full e-commerce platform with a custom admin panel so their team could manage products, orders, and customers without any technical knowledge. layer1.studio" },
  { id:8,  week:8,  template:'Stat',        theme:'DeepGreen',      cta:'', headline:'Premium chocolate deserves a premium digital presence.',                 subtext:'We built an e-commerce store and admin system that matches the quality of the product.',                             caption:"When a premium chocolate brand comes to you, the build has to match the product. We built Chocolatier's full e-commerce platform and admin panel — clean, fast, and built to convert. layer1.studio" },
  { id:9,  week:9,  template:'Quote',       theme:'NavyPurple',     cta:'', headline:'Art deserves to be seen. We built the platform to show it.',             subtext:'Portfolio meets e-commerce — a complete digital home for a creative business.',                                      caption:'A painter needed both a portfolio and a store. We built both — a beautiful portfolio that showcases the work and an e-commerce system that sells it. One platform. One build. layer1.studio' },
  { id:10, week:10, template:'Story',       theme:'CharcoalOrange', cta:'', headline:"From website to app — one client's full digital journey.",               subtext:'We built the website first. Then the app. Now their members never need to call.',                                    caption:'A local gym came to us for a website. A few months later they came back for a mobile app. Now their members book classes, track sessions, and get updates — all from their phone. layer1.studio' },
  { id:11, week:11, template:'BigHeadline', theme:'MidnightCoral',  cta:'', headline:'The cheapest website will cost you the most.',                           subtext:"A site that breaks, loads slowly, or can't be updated will lose you customers daily.",                               caption:"We see it constantly — businesses that went cheap on their website and are now paying twice to fix it. A digital foundation built properly the first time saves you money, customers, and stress. layer1.studio" },
  { id:12, week:12, template:'Stat',        theme:'NavyBlue',       cta:'', headline:'What if you could run your whole business from one screen?',             subtext:'No more juggling apps. No more WhatsApp chaos. Just one clean dashboard.',                                          caption:"An admin panel isn't a luxury — it's the difference between a business you control and one that controls you. Every website we build at Layer1 comes with a custom admin panel built around how you actually work. layer1.studio" },
  { id:13, week:13, template:'Split',       theme:'NavyTeal',       cta:'', headline:'Most Sri Lankan e-commerce sites lose customers at checkout.',           subtext:'Slow load times, confusing navigation, and no mobile optimisation. We fix all three.',                              caption:"We've audited enough local e-commerce sites to know the three things that kill conversions — slow loading, bad mobile experience, and a checkout process that has too many steps. We build to avoid all three from day one. layer1.studio" },
  { id:14, week:14, template:'Quote',       theme:'DeepGreen',      cta:'', headline:"We don't just build what you ask for.",                                  subtext:'We ask why first. Then we build what you actually need.',                                                           caption:"Every Layer1 project starts with one question — what problem are we actually solving? Not what does the website need to look like. What does your business need to do. That question changes everything about the build. layer1.studio" },
  { id:15, week:15, template:'Story',       theme:'NavyPurple',     cta:'', headline:'We build with tools that last.',                                         subtext:"No trendy frameworks that break in a year. Just clean, maintainable code built to grow with your business.",         caption:"We're opinionated about our stack — not because we're rigid, but because we've seen what happens when businesses are locked into technology that can't scale. We build with tools your business won't outgrow. layer1.studio" },
  { id:16, week:16, template:'BigHeadline', theme:'NavyTeal',       cta:'', headline:'We invest in the next generation of Sri Lankan developers.',             subtext:"Our interns don't make coffee. They ship code.",                                                                    caption:'At Layer1 we mentor young Sri Lankan developers by giving them real work on real projects. Our interns contribute to live client builds from day one. Because the best way to learn is to build something that actually matters. layer1.studio' },
  { id:17, week:17, template:'Stat',        theme:'MidnightCoral',  cta:'', headline:'Technology built for people who care for people.',                       subtext:"We built Connect to Care's digital presence to help them reach the communities they serve.",                          caption:"Connect to Care needed a digital platform that reflected their mission. We built a clean, accessible website that communicates their work clearly and makes it easy for people to find the support they need. layer1.studio" },
  { id:18, week:18, template:'CTA',         theme:'NavyBlue',       cta:"Book a call. Let's build it.", headline:"Have an idea? Let's shape it into something real.", subtext:'We take your brief from concept to launched product — on time, on budget, built to last.', caption:"If you have a business idea that needs a digital foundation — a website, an app, an e-commerce store, or all three — let's talk. We'll tell you honestly what you need and build it properly. layer1.studio" },
  { id:19, week:19, template:'Split',       theme:'CharcoalOrange', cta:'', headline:'We build websites. We also publish AI research.',                        subtext:'That combination means we think differently about technology — and build accordingly.',                              caption:"Layer1's technical co-founder also publishes AI research at international IEEE conferences. That's not a coincidence — it's why we approach every build with the same rigour we'd apply to a research problem. layer1.studio" },
  { id:20, week:20, template:'CTA',         theme:'DeepGreen',      cta:"Book a call. Let's build your foundation.", headline:"Sri Lanka's digital economy is growing. Is your business ready?", subtext:'The businesses that build their digital foundation now will lead their industry in five years.', caption:"Sri Lanka's e-commerce and digital services sector is growing fast. The businesses investing in proper digital infrastructure today — clean websites, apps, systems — are the ones that will own their markets in five years. We build those foundations. layer1.studio" },
]
